name: Deployment

on:
  push:
    branches: [ development ]

jobs:
  build:
    needs: deploy-development
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build assets
        run: npm run dev

  deploy-development:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USERNAME }}
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            cd /var/www/dev.siwira.my.id/html
            git checkout -- .
            git pull
            php artisan migrate
            composer install --ignore-platform-reqs
